### ISSUE TITLE
#9 : Prepare for Backend Integration

### ISSUE THREAD

**Issue by Sweetdevil144** [Sweetdevil144/Cat-GPT#10]
## Description
- Set up environment variables (use `.sample.env`) and prepare API utility functions for connecting to the backend.
- Document the API schema expected and prepare mock functions to simulate API calls.
- Ensure that components are ready to integrate with real-time data without major refactoring.

**Comment by Lokeshranjan8** [comment]
@Sweetdevil144  i would like to work on this issue

**Comment by Sweetdevil144** [comment]
I'd prefer you working on rest of Issues before winding up this one
