### ISSUE TITLE
#10 : Update Backend with Ollama

### ISSUE THREAD

**Issue by Sweetdevil144** [Sweetdevil144/Cat-GPT#16]
Ollama llama3 Integration doesn't work for now.

Changes can be made in : 

- Dockerfile
- Middleware Folder

**Comment by criticic** [comment]
I'd like to work on this, but what's the scope of this issue?

**Comment by Sweetdevil144** [comment]
What do you mean when you refer to scope?

**Comment by criticic** [comment]
As in what are the deliverables?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sweetdevil144** [comment]
Setting Up a custom API endpoint. Btw, you can decide to work on it, else I was thinking to tackle it myself
