### ISSUE TITLE
#2 : Develop a Chat Message Component

### ISSUE THREAD

**Issue by Sweetdevil144** [Sweetdevil144/Cat-GPT#3]
## Description
- Design and implement a `Message` component to display messages from both the user and the AI.
- The component should handle different types of messages (text, links, and possibly images).
- Ensure responsiveness and readability across devices.

**Comment by Lokeshranjan8** [comment]
@Sweetdevil144 i would like to work on this .

**Comment by Sweetdevil144** [comment]
Yeah sore. Go ahead

**Comment by Lokeshranjan8** [comment]
@Sweetdevil144  could you please clarify if we need to link the input area (user input) in a way that displays the messages above the chat area when typed?

**Comment by Sweetdevil144** [comment]
> @Sweetdevil144 could you please clarify if we need to link the input area (user input) in a way that displays the messages above the chat area when typed?

For now, YES. As we proceed with our Backend, we'll further couple this with our Messages. For now, design a simple message dialogue box with two categories :
- User
- Ollama

Each Facing Opposite directions. Take `Wp` as inspiration.

**Comment by Lokeshranjan8** [comment]
![Uploading msg.png…]()
is it good?

**Comment by Lokeshranjan8** [comment]
![msg11](https://github.com/Sweetdevil144/Cat-GPT/assets/146512765/6206128e-d441-4fd4-95a4-565b5b69e080)

**Comment by Sweetdevil144** [comment]
LGTM. Can you make a PR soon? I'll need to merge a PR by @criticic after these changes are introduced.
