### ISSUE TITLE
#4 : Setup State Management for Messages

### ISSUE THREAD

**Issue by Sweetdevil144** [Sweetdevil144/Cat-GPT#5]
## Description
- Implement state management using Context API or Redux to handle the flow of messages.
- The state should update upon sending and receiving messages.
- Prepare dummy functions for sending and receiving messages.

NOTE : We'll work on the backend later on. So this task should be done using dummy api calls. A simple predictive api system can also be utilised.

However, if folks face difficulties, I'll push the backend code to make the API available.

Difficulty : Medium

**Comment by Lokeshranjan8** [comment]
@Sweetdevil144  I would like to work on this, what we should prefer  context API or Redux

**Comment by Sweetdevil144** [comment]
As you feel easy and good.
