### ISSUE TITLE
#5 : Integrate Basic Styling and Theme

### ISSUE THREAD

**Issue by Sweetdevil144** [Sweetdevil144/Cat-GPT#6]
## Description
- Establish a consistent color scheme and font style for the UI.
- Ensure the design is visually appealing and accessible.

**Comment by criticic** [comment]
I'd like to work on this!

**Comment by criticic** [comment]
So my plan is to use colors from Material 3 (not widgets just the colors)

This will allow us to have a complete pallete for colors for both light and dark mode, and also make sure its accessible

**Comment by criticic** [comment]
Do you have a specific color in mind, which can be used as the seed color?

**Comment by Sweetdevil144** [comment]
>Do you have a specific color in mind, which can be used as the seed color?

Something that has a good combo b/w fluorescent green and Grey. Other than that, I'd leave it entirely upto you.

**Comment by criticic** [comment]
I tried going with a saturated blue, here is how it looks (added some more info too)
![image](https://github.com/Sweetdevil144/Cat-GPT/assets/40538506/b59b2f34-fe4f-414b-81a5-b75f8045a647)
![image](https://github.com/Sweetdevil144/Cat-GPT/assets/40538506/0d4efd2f-170c-4cb0-abf7-304c0dc1f209)

Based on the seed color, the surface, background colors will differ,
for eg with a flouroscent green type color:

![image](https://github.com/Sweetdevil144/Cat-GPT/assets/40538506/7c39e6a1-103e-44b3-a278-d895ba626202)
![image](https://github.com/Sweetdevil144/Cat-GPT/assets/40538506/acb29c53-98c2-4498-ba72-b64ceaa9f22d)

**Comment by Sweetdevil144** [comment]
The second look better !!

**Comment by criticic** [comment]
what about the outlines?

**Comment by Sweetdevil144** [comment]
LGTM !! As I said, the final submission ultimately depends on you. I'll proceed with the best build you rovide. Outlines are necessary in cards
